Fix/design
ODIN-PROTOCOL/odin-web pull request #1
Opened 2022-05-02 11:55 UTC by nikita1tup

2022-05-02 16:10 UTC, ArtSuslov requested changes

2022-05-02 16:10 UTC, ArtSuslov commented on src/views/DataSources.vue
> +    const sortingActivitiesValue = ref('latest_updated')
ACTIVITIES_SORT.latest (and fix that enum, key should be presented in camel case)

2022-05-02 16:10 UTC, ArtSuslov commented on src/views/OracleScripts.vue
> +    const sortingActivitiesValue = ref('latest_updated')
!

2022-05-02 16:10 UTC, ArtSuslov commented on src/views/Proposal.vue
> +              :href="`${API_CONFIG.odinScan}/account/${proposal?.proposerAddress}`"
is it expected flow when there is no proposerAddress and link gets broken?

2022-05-02 16:55 UTC, nikita1tup commented on src/components/modals/ModalBase.vue
> +        :class="{ 'mg-b32': isAddMargin }"
i need to change UndelegateFromModal, in this component i can't remove margin due to scope. If I remove the scope, then the margin will also be removed in other modals

2022-05-03 09:29 UTC, ArtSuslov requested changes

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/LinksDropdown.vue
> +.arrow-icon_active {
discussed

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/LinksDropdown.vue
> +.nav__dropdown {
lets make it the way - if you work on some component and classnames did not follow BEM, you just rename them all over that component

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/LinksDropdown.vue
> +    border-bottom: 0.1rem solid #ced4da;
var(--clr__input-border);

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/LinksDropdown.vue
> +    border-bottom: 0.1rem solid #ced4da;
!

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/LinksDropdown.vue
> +    border-bottom: 0.1rem solid #ced4da;
!

2022-05-03 09:29 UTC, ArtSuslov commented on src/components/modals/UndelegateFormModal.vue
> +.copy-text {
?

2022-05-03 09:29 UTC, ArtSuslov commented on src/views/Wallet.vue
> +              class="info__card-row-value"
component's name is Wallet, not Info

2022-05-03 09:29 UTC, ArtSuslov commented on src/views/Wallet.vue
> +      <div class="view-main__info">
same here

2022-05-03 09:29 UTC, ArtSuslov commented on src/views/Wallet.vue
> +  &__info {
no waterfalls

2022-05-05 13:00 UTC, merged