fix clear button on searchbar
ODIN-PROTOCOL/odin-web pull request #13
Opened 2022-06-24 10:23 UTC by OscarFlay96

2022-06-27 16:06 UTC, nikita1tup commented on src/views/Validators.vue
> +                :className="'validators__filter-search__cancel-button'"
don't use v-bind. className="validators__filter-search__cancel-button". It will be better

2022-06-27 16:07 UTC, nikita1tup commented on src/views/Validators.vue
> +  right: 0rem;
rem

2022-06-27 16:11 UTC, nikita1tup commented on src/views/Validators.vue
> +                :className="'validators__filter-search__cancel-button'"
and use BEM

2022-06-30 11:02 UTC, ArtSuslov requested changes

2022-06-30 11:02 UTC, ArtSuslov commented on src/components/Search.vue
> +        <template v-if="data.searchValue">
move it into InputField so you don't need to repeat this code each time you use search (DRY)

2022-07-19 15:11 UTC, ArtSuslov requested changes

2022-07-19 15:11 UTC, ArtSuslov commented on src/components/Search.vue
> +        </InputField>
<InputField />

2022-07-19 15:11 UTC, ArtSuslov commented on src/components/Search.vue
> +import CancelIcon from '@/components/icons/CancelIcon.vue'
never used

2022-07-19 15:11 UTC, ArtSuslov commented on src/components/SortLine.vue
> +          classString="sort-line__search-input"
can you clarify this decision? class="sort-line__search-input" will apply on input as well,

2022-07-20 08:34 UTC, OscarFlay96 commented on src/components/SortLine.vue
> +          classString="sort-line__search-input"
i was trying to apply the styles in the SortLine class to the InputField component because the button for search needs too have the same behaviour as the cancel, and the search button is not inside the inputField, it should be inside as the cancel button?

2022-07-26 12:58 UTC, merged