Feature/Frontend visible no auth
ODIN-PROTOCOL/odin-web pull request #19
Opened 2022-07-04 07:43 UTC by yeraycat

2022-07-07 11:36 UTC, ArtSuslov requested changes

2022-07-07 11:36 UTC, ArtSuslov commented on src/App.vue
> +    <template v-if="!hideNav">
boolean variables should be prefixed with 'is'

2022-07-07 11:36 UTC, ArtSuslov commented on src/components/Nav.vue
> +    <div class="nav__activities" v-if="isLoggedIn">
v-if should go [first](https://v2.vuejs.org/v2/style-guide/?redirect=true#Element-attribute-order-recommended)

2022-07-07 11:36 UTC, ArtSuslov commented on src/components/SortLine.vue
> +// import { useAuthorization } from '@/composables/useAuthorization'
comments should be meaningful or removed

2022-07-07 11:36 UTC, ArtSuslov commented on src/components/SortLine.vue
> +    const walletAddress = wallet.isEmpty ? ' ' : wallet.account.address
is it okay to use non-empty string in this case?

2022-07-07 11:36 UTC, ArtSuslov commented on src/components/SortLine.vue
> +      walletAddress,
not being used, no need to return

2022-07-07 11:36 UTC, ArtSuslov commented on src/components/ValidatorInfo.vue
> +          v-if="accountAddress"
!

2022-07-08 07:02 UTC, yeraycat commented on src/components/ValidatorsTableRow.vue
> +    showActionButtons: { type: Boolean, required: true },
Can I use `has` instead of `is`?

2022-07-08 07:11 UTC, yeraycat commented on src/components/SortLine.vue
> +    const walletAddress = wallet.isEmpty ? ' ' : wallet.account.address
It was a typo I think

2022-07-13 07:28 UTC, nikita1tup commented on src/views/Requests.vue
> +    <div class="view-main__mobile-activities" v-if="accountAddress">
v-if should go first

2022-07-13 08:56 UTC, yeraycat commented on src/views/Requests.vue
> +    <div class="view-main__mobile-activities" v-if="accountAddress">
Yep, sorry for that. Fixed.

2022-07-13 11:48 UTC, merged